#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/config/bootstrap.php';

$config = require __DIR__ . '/config/console.php';

exit((new yii\console\Application($config))->run());
